version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: alejary/node:1
    ports:
      - "3000:3000"
    networks:
      - webnet
networks:
  webnet: